language: rust
addons:
  apt:
    packages:
      - nasm

before_install:
    - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
    - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr
    - sudo rm -fR /usr/local/cmake*
    - hash -r
    - which cmake
    - cmake --version
    - wget https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz
    - tar -xvf nasm-2.13.03.tar.xz
    - cd nasm-2.13.03
    - ./configure
    - make
    - sudo make install
    - nasm --version
script:
    - |
        cargo build --verbose &&
        cargo test --verbose &&
        cargo test --verbose --release --features=decode_test -- --ignored &&
        cargo bench --verbose &&
        cargo doc --verbose
